import "./main.css";

export const metadata = {
  title: "Graphoblog",
  description: "Generated by create next app",
  
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    {/* // Remove the font link from layout.js */}
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />
      <link rel="icon" href="favicon.ico" sizes="any" />
      <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
  />
    </head>
      <body>{children}</body>
    </html>
  );
}

